---
- name: Deploy Docker container from Nexus
  hosts: sonar
  become: yes

  vars:
    image_name: "vprofile"
    image_tag: "latest"
    nexus_registry: "3.88.248.130:8082"
    nexus_username: "admin"
    nexus_password: "YassineNexus12**"

  tasks:
    - name: Authenticate to Nexus Docker registry
      shell: echo "{{ nexus_password }}" | docker login {{ nexus_registry }} -u {{ nexus_username }} --password-stdin

    - name: Pull Docker image from Nexus
      shell: docker pull {{ nexus_registry }}/{{ image_name }}:{{ image_tag }}

    - name: Stop running container if exists
      shell: docker stop {{ image_name }} || true

    - name: Remove existing container if exists
      shell: docker rm {{ image_name }} || true

    - name: Run Docker container
      shell: |
        docker run -d --name {{ image_name }} -p 8080:8080 \
        {{ nexus_registry }}/{{ image_name }}:{{ image_tag }}
