---
- name: Deploy Docker container from Nexus
  hosts: sonar
  become: yes

  vars:
    image_name: "vprofile"
    image_tag: "latest"  # Ce sera mis à jour dynamiquement plus tard si besoin
    nexus_registry: "3.88.248.130:8082"

  tasks:
    - name: Pull Docker image from Nexus
      shell: docker pull {{ nexus_registry }}/{{ image_name }}:{{ image_tag }}

    - name: Stop running container if exists
      shell: docker stop {{ image_name }} || true

    - name: Remove existing container if exists
      shell: docker rm {{ image_name }} || true

    - name: Run Docker container
      shell: |
        docker run -d --name {{ image_name }} -p 8080:8080 \
        {{ nexus_registry }}/{{ image_name }}:{{ image_tag }}

